# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2c89b9d47c5ff7bc896c24ead8da9a0e48fa75d57e9ccab0dd4e1a6d43b48b297a4803e1d86be20315c132c24b5be2d1840f9d782467ad424afbf3d1e2b50c0a

test:
  secret_key_base: 6cd1db11a1c33c1cb31567ea1e545a2a71f1a869b4a534a5d1ab6b7d1de48e7ff96244601699a1761dcb6b49042e7debf0cd08877a0a8c651574de7509c83078

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
